[package]
name = "no-nonsense-flamegraphs"
version = "0.2.0"
authors = ["Justin Pombrio"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inferno = "0.10.*"
